version: 2.1
jobs:
  build_and_test:
    resource_class: large
    docker:
      - image: cimg/go:1.18
    steps: # steps that comprise the `build` job
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libx11-dev libgl1-mesa-dev xorg-dev
      - run: make test
