version: 2.1
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14
    
    #working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps: # steps that comprise the `build` job
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libx11-dev
  test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14
    steps:
      - run: make test

workflows:
  build_and_test:
    jobs:
      - build
      - test