version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14
    
    #working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps: # steps that comprise the `build` job
      - checkout
      - run: make test
