version: 2.1
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14
    steps: # steps that comprise the `build` job
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libx11-dev libgl1-mesa-dev xorg-dev
      - run: make test
